name: Build robotgo-opencv

on:
  workflow_dispatch:
  push:
    paths:
      - robotgo-opencv/**
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: robotgo-opencv/robotgo-opencv.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/robotgo-opencv:latest